
---
- name: Configure OSPF on Arista Routers
  hosts: all
  gather_facts: false

  tasks:
    - name: Enable OSPF routing process
      arista.eos.eos_config:
        lines:
          - "router ospf 1"
        save_when: modified
      register: my_output

    - debug: var=my_output



